In [43]:
#Importando bibliotecas nescessarias
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

In [44]:
#Carregando os dados
treino = pd.read_csv(r"csv/train.csv")
teste = pd.read_csv(r"csv/test.csv")

print("Colunas")
print("-----------------------------------------")
print(treino.columns)
print(teste.columns)
print("-----------------------------------------")
#Organizacao inicial dos dados

#Alterando colunas para valores numericos
treino["Sex"] = treino["Sex"].map({
    "male": 0,
    "female": 1,
})
teste["Sex"] = teste["Sex"].map({
    "male": 0,
    "female": 1,
})

treino = pd.get_dummies(treino, columns=["Embarked"], drop_first=True)
teste = pd.get_dummies(teste, columns=["Embarked"], drop_first=True)

treino.head()

Colunas
-----------------------------------------
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')
Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')
-----------------------------------------

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,False,False
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,False,True
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,False,True

In [45]:
print("Verificando valores nulos")
print("-----------------------------------------")
print(treino.isna().sum())
print("-----------------------------------------")

treino[treino['Age'] < 1]

Verificando valores nulos
-----------------------------------------
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked_Q       0
Embarked_S       0
dtype: int64
-----------------------------------------

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_Q,Embarked_S
78,79,1,2,"Caldwell, Master. Alden Gates",0,0.83,0,2,248738,29.0000,NaN,False,True
305,306,1,1,"Allison, Master. Hudson Trevor",0,0.92,1,2,113781,151.5500,C22 C26,False,True
469,470,1,3,"Baclini, Miss. Helene Barbara",1,0.75,2,1,2666,19.2583,NaN,False,False
644,645,1,3,"Baclini, Miss. Eugenie",1,0.75,2,1,2666,19.2583,NaN,False,False
755,756,1,2,"Hamalainen, Master. Viljo",0,0.67,1,1,250649,14.5000,NaN,False,True
803,804,1,3,"Thomas, Master. Assad Alexander",0,0.42,0,1,2625,8.5167,NaN,False,False
831,832,1,2,"Richards, Master. George Sibley",0,0.83,1,1,29106,18.7500,NaN,False,True

In [46]:
# 1. Calculamos a mediana usando apenas o conjunto de treinamento
mediana_idade = treino['Age'].median()

# 2. Preenchemos os valores nulos em ambos os conjuntos
treino['Age'] = treino['Age'].fillna(mediana_idade)
teste['Age'] = teste['Age'].fillna(mediana_idade)

In [47]:
#Armazenando os ids para envio no kaggle competition
id_treino = treino["PassengerId"]
id_teste = teste["PassengerId"]

#Excluindo colunas irrelevantes para o proposito
X_treino = treino.drop(columns=["Name", "Survived","PassengerId","Ticket","Cabin"])
X_teste = teste.drop(columns=["Name", "PassengerId","Ticket","Cabin"])

#Armazenando o alvo
y_treino = treino["Survived"]

X_treino.head()

   Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_Q  Embarked_S
0       3    0  22.0      1      0   7.2500       False        True
1       1    1  38.0      1      0  71.2833       False       False
2       3    1  26.0      0      0   7.9250       False        True
3       1    1  35.0      1      0  53.1000       False        True
4       3    0  35.0      0      0   8.0500       False        True